### ISSUE TITLE
[FEATURE] tag Model & tagView  구성

### ISSUE THREAD

**Issue by kwangjo93** [TeamPoki/Poki-iOS#11]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
tag Model & tagView 를 만들고 present 하기
## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] tag Model 만들기
- [x] tag data 만들기
- [x] tagView 만들기
- [x] 버튼 클릭 시 present 후 선택 시 저장

## ETC
> 기타 참고사항이 있으면 작성하세요.
