### ISSUE TITLE
[FEATURE] 로그인/회원가입 페이지 UI 수정

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#112]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
- 회원가입 페이지 UI 수정

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

-로그인 페이지
- [x] 비밀번호 보기 버튼 구현
- [x] 코멘트 수정
- [x] 이메일/아이디 저장 버튼 액션 구현

- 회원가입 페이지
- [x] 가입하기 버튼 위치 수정
- [x] 닉네임 텍스트 필드 구현
- [x] 비밀번호 확인 텍스트 필드 제거
- [x] 비밀번호 보기 버튼 구현
- [x] 이용 약관 동의 버튼 구현

## ETC
> 기타 참고사항이 있으면 작성하세요.
