### ISSUE TITLE
[FEATURE] 포즈 추천 페이지 UI 구현

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#12]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
- 포즈 추천 페이지 UI 구현
- 랜덤 포즈 추천 페이지 UI 구현

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] 포즈 추천 페이지 - 인원 수 별 버튼 구현
- [x] 포즈 추천 페이지 - 인원 수 별 버튼을 눌렀을 때, 랜덤 포즈 추천 페이지로 전환
- [x] 랜덤 포즈 추천 페이지 - 메인 이미지 뷰 구현
- [x] 랜덤 포즈 추천 페이지 - "다른 포즈보기" 버튼 구현
- [x] 랜덤 포즈 추천 페이지 - 즐겨찾기 버튼 구현

## ETC
> 기타 참고사항이 있으면 작성하세요.
- 포즈 추천 페이지에서 버튼을 눌렀을 때, 랜덤 포즈를 추천해주는 화면이 하나 더 필요해서 같이 구현하겠습니다.
