### ISSUE TITLE
[FEATURE] 시작 화면 및 로그아웃 시 화면 전환 방식 변경

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#133]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
SceneDelegate 에서 RootViewController 를 변경해서 로그인, 로그아웃 시 화면 전환 구현

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] SceneDelegate - changeRootViewContoller 메서드 구현
- [x] 기존 화면 전환 방식 삭제
- [x] changeRootViewContoller 메서드 적용

## ETC
> 기타 참고사항이 있으면 작성하세요.
