### ISSUE TITLE
[FEATURE] 회원가입 페이지 유효성 검사 구현 및 레이아웃 수정

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#138]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
- 회원가입 페이지 유효성 검사 구현
- 레이아웃 수정 및 텍스트 필드 간격 조정

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.
- [x] 유효성 검사를 위한 정규 표현식 정의
- [x] 유효성 검사 로직 구현
- [x] 유효성 검사 구현 후 확인
- [x] 레이아웃 수정 및 텍스트 필드 간격 조정

## ETC
> 기타 참고사항이 있으면 작성하세요.
