### ISSUE TITLE
[FEATURE] 로그인 페이지 및 회원가입 페이지 UI 수정

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#144]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
로그인 페이지 및 회원가입 페이지 UI 수정

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- 로그인 페이지
- [x] 이메일 저장 버튼 크기 수정
- [x] 텍스트 필드 커서 색상 변경

- 회원가입 페이지
- [x] 텍스트 필드 테두리 높이 수정

## ETC
> 기타 참고사항이 있으면 작성하세요.
