### ISSUE TITLE
[FEATURE] 로그인 페이지 텍스트 필드 설정 추가 및 상태 바 컬러 추가

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#162]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
로그인 페이지의 텍스트 필드 키보드 설정 추가 및 상태바 컬러 추가

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] 텍스트 필드 소문자 입력 설정
- [x] 텍스트 필드 자동 수정 설정
- [x] 텍스트 필드 오류난 글자 수정 설정
- [x] 상태바 색상 지정

## ETC
> 기타 참고사항이 있으면 작성하세요.
