### ISSUE TITLE
[FEATURE] 토스트 뷰 사이즈 수정 및 포즈 추천 페이지 UI 수정

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#194]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
- 토스트 뷰 사이즈 수정 및 포즈 추천 페이지 UI 수정

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] 토스트 뷰 사이즈 수정
- [x] 포즈 추천 페이지 전체 컴포넌트 간격 조정
- [x] 포즈 추천 페이지 배경색 및 테두리 변경

## ETC
> 기타 참고사항이 있으면 작성하세요.
