### ISSUE TITLE
[FEATURE] 상세 페이지(DetailPage) UI 구현

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#2]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
상세 페이지 UI 구현

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.
- [x] 타이틀 레이블 구현
- [x] 날짜 레이블 구현
- [x] 메인 이미지 뷰 구현
- [x] 배경 이미지 뷰 구현

## ETC
> 기타 참고사항이 있으면 작성하세요.
