### ISSUE TITLE
[FIX] 이메일 및 닉네임 정규표현식 변경 및 적용

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#305]
## Description
> 어떤 버그로 인한 작업인지 설명하세요.
- 이메일 및 닉네임에 입력할 수 있는 특수문자(`,` `.` `-`) 추가 및 닉네임 정규표현식 공백 입력 못하도록 수정

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] 이메일 정규표현식 수정
- [x] 닉네임 정규표현식 수정
- [x] 태그 이미지 압축률 수정

## ETC
> 기타 참고사항이 있으면 작성하세요.
- 추가적으로 태그 이미지 압축률도 함께 수정하겠습니다.
