### ISSUE TITLE
[FIX] 로그인 시 사용성 개선을 위한 UI 수정 및 포즈 추천 이미지 추가

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#313]
## Description
> 어떤 버그로 인한 작업인지 설명하세요.
- 로그인 페이지 UI 수정 및 사용성 개선
- 포즈 추천 이미지 추가

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.
- [x] 로그인 페이지 - 텍스트 필드의 클린 버튼과 비밀번호 보기 버튼의 위치가 맞지 않아서 비밀번호 보기 버튼 레이아웃 수정
- [x] 로그인 페이지 - 이메일 또는 비밀번호를 누르지 않았을 때도 토스트 뷰를 띄우도록 수정
- [x] 포즈 추천 이미지 추가

## ETC
> 기타 참고사항이 있으면 작성하세요.
