### ISSUE TITLE
[FEATURE] : MainPageViewController 에서 Read 구현

### ISSUE THREAD

**Issue by Insuuu24** [TeamPoki/Poki-iOS#71]
## Description
> 추가하기 페이지에서 추가하고 메인페이지에서 추가한 데이터 보여지게 하기 

## Task
- [ ] UICollectionView, numberOfItemsInSection 설정 변경
- [ ] UICollectionView, cellForItemAt 설정 변경
- [ ] UICollectionView, didSelectItemAt 설정 변경

## ETC
> -
