### ISSUE TITLE
[FEATURE] 포즈 추가 및 포즈 추천 페이지 UI 수정

### ISSUE THREAD

**Issue by playhong16** [TeamPoki/Poki-iOS#96]
## Description
> 어떤 작업을 진행할지 간단하게 내용 작성하세요.
- 포즈 추천 페이지에 UI 수정 및 사진 추가

## Task
> 진행하는 작업을 작은 단위로 분리해서 작성하세요.

- [x] 포즈 사진 추가
- [x] 이미지뷰 크기 조정
- [x] 버튼 크기 조정 및 속성 변경

## ETC
> 기타 참고사항이 있으면 작성하세요.
